name: Disable Branch Protection

on:
  workflow_dispatch:

jobs:
  disable-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Disable Branch Protection
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          
          curl -X PATCH \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/amirfakhrullah/electron-reac/branches/main/protection" \
            -d '{
              "restrictions": null,
              "required_status_checks": null,
              "enforce_admins": false
            }'
