name: Deployment

on:
  push:
    branches:
      - main

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Read package.json
        id: read_package_json
        run: |
          echo "version=$(node -p "require('./release/app/package.json').version")" >> $GITHUB_OUTPUT

      - name: Increment version
        id: increment_version
        run: |
          VERSION=$(echo "${{ steps.read_package_json.outputs.version }}")
          MAJOR=$(echo "$VERSION" | cut -d. -f1)
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          PATCH=$(echo "$VERSION" | cut -d. -f3)
          NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update version in package.json & package-lock.json
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.increment_version.outputs.new_version }}\"/" release/app/package.json
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.increment_version.outputs.new_version }}\"/" release/app/package-lock.json

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "Release v${{ steps.increment_version.outputs.new_version }} [skip ci]"
          git push


  build-win:
    needs: increment-version
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest
        run: |
          git pull
          git merge main

      - name: Install dependencies
        run: npm i

      - name: Build Electron app
        run: npm run package -- --win

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-build-win
          path: release/build

  create-release:
    needs: build-win
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download release builds
        uses: actions/download-artifact@v2
        with:
          name: release-build-win
          path: release/build

      - name: Get the latest version from latest.yml
        id: read_yml_version
        run: |
          VERSION=$(yq eval '.version' ./release/build/latest.yml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        run: |
          echo "Creating a release for version v${{ steps.read_yml_version.outputs.version }}"
          RESPONSE=$(curl -L \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28"\
            https://api.github.com/repos/amirfakhrullah/electron-react/releases \
            -d '{
            "tag_name": "v${{ steps.read_yml_version.outputs.version }}",
            "name": "Release v${{ steps.read_yml_version.outputs.version }}",
            "draft": false,
            "prerelease": false,
            "generate_release_notes":true
          }')
          echo "upload_url=$(echo "$RESPONSE" | jq -r '.upload_url' | sed -e "s/{?name,label}//")" >> $GITHUB_OUTPUT

      - name: Upload release assets
        id: upload_assets
        run: |
          FILE_PATH=$(find ./release/build -name "*Setup*.exe" | head -n 1)
          FILE_NAME="ElectronReact-${{ steps.read_yml_version.outputs.version }}-win.exe"
          curl -L \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/zip" \
            --data-binary "@$NEW_FILE_PATH" \
            "${{ steps.create_release.outputs.upload_url }}?name=$FILE_NAME"

      - name: Delete Artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: release-build-win




          # NEW_FILE_PATH="./release/build/$NEW_FILE_NAME"
          # mv "$FILE_PATH" "$NEW_FILE_PATH"