name: Deployment

on:
  push:
    tags:
      - '*'

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # - name: Read package.json
      #   id: read_package_json
      #   run: |
      #     echo "version=$(node -p "require('./release/app/package.json').version")" >> $GITHUB_OUTPUT
          # VERSION=$(echo "${{ steps.read_package_json.outputs.version }}")

      - name: Increment version
        id: increment_version
        run: |
          VERSION=${{ github.ref }}
          MAJOR=$(echo "$VERSION" | cut -d. -f1)
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          PATCH=$(echo "$VERSION" | cut -d. -f3)
          NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update package.json
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.increment_version.outputs.new_version }}\"/" release/app/package.json

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "Bump version [skip ci]"
          git push

  build-and-package:
    needs: increment-version
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm i

      - name: Build Electron app
        run: npm run package -- --win

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-builds
          path: release/build

  create-release:
    needs: build-and-package
    runs-on: ubuntu-latest

    steps:
      - name: Download release builds
        uses: actions/download-artifact@v2
        with:
          name: release-builds
          path: release/build

      - name: Upload builds to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: release/build/*Setup*.exe
          asset_name: build
          overwrite: true


