name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # bump version ============================

      - name: Read version of package.json
        id: read_version
        run: |
          echo "version=$(node -p "require('./release/app/package.json').version")" >> $GITHUB_OUTPUT

      - name: Increment version
        id: increment_version
        run: |
          VERSION=$(echo "${{ steps.read_version.outputs.version }}")
          MAJOR=$(echo "$VERSION" | cut -d. -f1)
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          PATCH=$(echo "$VERSION" | cut -d. -f3)
          NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update package.json & package-lock.json
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.increment_version.outputs.new_version }}\"/" release/app/package.json
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.increment_version.outputs.new_version }}\"/" release/app/package-lock.json

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "Release v${{ steps.increment_version.outputs.new_version }} [skip ci]"
          git push

      # build and package ============================

      - name: Install dependencies
        run: npm i

      - name: Build Electron app
        run: npm run package -- --win

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: release

  create-release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download release builds
        uses: actions/download-artifact@v2
        with:
          name: release
          path: release-latest

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Read version of package.json
        id: release_version
        run: |
          echo "new_version=$(node -p "require('./release-latest/build/app/package.json').version")" >> $GITHUB_OUTPUT

      # - name: Compress builds
      #   run: |
      #     7z a -r release/build.zip release/build-latest

      - name: Create release
        id: create_release
        run: |
          echo "response=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28"\
            https://api.github.com/repos/amirfakhrullah/electron-react/releases \
            -d '{
            "tag_name": "v${{ steps.release_version.outputs.new_version }}",
            "name": "Release v${{ steps.release_version.outputs.new_version }}",
            "draft": false,
            "prerelease": false,
            "generate_release_notes":true
          }')" >> $GITHUB_OUTPUT

      # - name: Upload builds to the release
      #   run: |
      #     curl -L \
      #     -X POST \
      #     -H "Accept: application/vnd.github+json" \
      #     -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
      #     -H "X-GitHub-Api-Version: 2022-11-28" \
      #     -H "Content-Type: application/zip" \
      #     https://uploads.github.com/repos/amirfakhrullah/electron-react/releases/${{ steps.create_release.outputs.release_id }}/assets?name=build.zip \
      #     --data-binary "@release/build.zip"

      - name: Upload release assets
        id: upload_assets
        run: |
          RESPONSE=${{ steps.create_release.outputs.response }}
          RELEASE_ID=$(echo $RESPONSE | jq -r '.id')
          UPLOAD_URL=$(echo $RESPONSE | jq -r '.upload_url' | sed -e "s/{?name,label}//")
          ASSET_PATH="release-latest/build/*Source*.exe"
          for file in $ASSET_PATH; do
            echo "Uploading $file..."
            curl -L \
              -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: $(file -b --mime-type $file)" \
              --data-binary @$file \
              "$UPLOAD_URL?name=$(basename $file)&label=$(basename $file)"
          done



