name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm i

      - name: Build Electron app
        run: npm run package -- --win

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-builds
          path: release/build

  notify-discord:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download release builds
        uses: actions/download-artifact@v2
        with:
          name: release-builds
          path: release/build

      - name: Send release build to Discord
        run: |
          export WEBHOOK_URL="${{ secrets.DISCORD_WEBHOOK_URL }}"
          for file in release/build/Setup*.exe; do
            curl -X POST -H "Content-Type: multipart/form-data" -F "file=@$file" $WEBHOOK_URL
          done
